### PR TITLE
Create docker.sh

### PR DESCRIPTION
**Pull request by cmungall**
Note odkfull has robot 1.1.0 currently, do you need 1.20-alpha?

### CODE REVIEW

**Comment by beckyjackson** [comment]
If it's not too much trouble, we cover the `remove` and `filter` commands at the end.

**Comment by beckyjackson** [comment]
I can always just add a note that the Docker method includes 1.1.0, though, and they'll be able to do everything else.

**Comment by cmungall** [comment]
I quote like having odkfull track main releases, but we can discuss this. Also a lot of people have already downloaded odkfull, they'd have to re-download, lots of people downloading 1g images.. 

Another option is to use a basic robot container. I can make a lightweight one using alpine that includes bash and make and is 140MB.

**Comment by beckyjackson** [comment]
This is great, thanks!

**Pull request merged**
